### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by bas4r**

### CODE REVIEW

**Review by surabhil — CHANGES_REQUESTED** [review]
- Why are we including eosio standard contracts in the ore protocol repo. if we do so, we would need to updgrade the current repo as well as maintain this forked repo: https://github.com/API-market/eosio.contracts
- It would be nice to only have ore-protocol stuff here. Having eosio contracts in the forked repo would give us a single point of truth instead of maintaining them at 2 places. Also, upgrading to latest eosio contract version would be easier.

**Comment by surabhil** [comment]
why are we replicating the code for ore_types under each contract /include directory instead of including ore.types.h from contracts/ore_types

**Comment by bas4r** [comment]
> * Why are we including eosio standard contracts in the ore protocol repo. if we do so, we would need to updgrade the current repo as well as maintain this forked repo: https://github.com/API-market/eosio.contracts
> * It would be nice to only have ore-protocol stuff here. Having eosio contracts in the forked repo would give us a single point of truth instead of maintaining them at 2 places. Also, upgrading to latest eosio contract version would be easier.

The problem was, new intermediary contract requires system contract for test, so I had to use eosio contract on the dev process. I could also add intermediary contract to eosio.contracts folder and have it's test there. I removed eosio contracts but left intermediary here for now.

**Comment by bas4r** [comment]
> why are we replicating the code for ore_types under each contract /include directory instead of including ore.types.h from contracts/ore_types

I wanned to have all of the included files for a cpp under include folder, but didn't want to remove ore_types folder as to make it easy to inspect, but we can choose one way and remove other.

**Pull request closed without merging**
